import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    env: {
      JWT_SECRET: 'supersecretjwtkeythatis16chars',
      SUPABASE_URL: 'https://test.supabase.co',
      SUPABASE_ANON_KEY: 'test-anon-key',
      SUPABASE_SERVICE_ROLE_KEY: 'test-service-key',
      GMAIL_USSER: 'test@example.com',
      GMAIL_PASS: 'testpass'
    },
    include: ['src/tests/**/*.test.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov'],
      reportsDirectory: 'coverage',
      reportOnFailure: true,
      include: [
        'src/domain/entities/LoanApplication.ts',
        'src/domain/entities/VirtualCard.ts',
        'src/domain/entities/User.ts',
        'src/domain/entities/VerificationCode.ts',
        'src/domain/entities/Notification.ts',
        'src/application/use-cases/loan/*.ts',
        'src/application/use-cases/card/*.ts',
        'src/application/use-cases/auth/*.ts',
        'src/application/use-cases/profile/GetProfile.ts',
        'src/application/use-cases/profile/UpdateProfile.ts',
        'src/application/use-cases/profile/UploadDocument.ts',
        'src/presentation/controllers/LoanController.ts',
        'src/presentation/controllers/CardController.ts',
        'src/presentation/controllers/AuthController.ts',
        'src/presentation/controllers/TwoFactorController.ts',
        'src/presentation/controllers/ProfileController.ts',
        'src/presentation/validators/loan.validators.ts',
        'src/presentation/validators/auth.validators.ts',
        'src/presentation/validators/profile.validators.ts',
        'src/presentation/middlewares/adminMiddleware.ts',
        'src/presentation/middlewares/authMiddleware.ts',
        'src/infrastructure/repositories/SupabaseLoanApplicationRepository.ts',
        'src/infrastructure/repositories/SupabaseVirtualCardRepository.ts',
        'src/infrastructure/repositories/SupabaseUserRepository.ts',
        'src/infrastructure/repositories/SupabaseVerificationCodeRepository.ts',
        'src/infrastructure/services/JwtTokenService.ts',
        'src/infrastructure/services/BcryptPasswordService.ts',
        'src/infrastructure/services/NodemailerEmailService.ts',
        'src/presentation/controllers/PocketController.ts',
        'src/infrastructure/repositories/SupabasePocketRepository.ts',
        // Bolsillos: entidad + casos de uso (pruebas unitarias AAA + 5 dobles)
        'src/domain/entities/Pocket.ts',
        'src/application/use-cases/pocket/*.ts',
        'src/shared/utils/*.ts',
        'src/shared/errors/*.ts',
        'src/domain/value-objects/*.ts',
      ],
      thresholds: {
        statements: 85,
        branches: 80,
        functions: 85,
        lines: 85,
      },
    },
  },
});
